# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "Use Ory from the your terminal!"
  homepage "https://www.ory.sh"
  version "0.1.32"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ory/cli/releases/download/v0.1.32/ory_0.1.32-macOS_sqlite_64bit.tar.gz"
      sha256 "9e4343b272190a63b9a47290f01ebf9511dcf24ed8687963a3d68ae89e4b6efc"

      def install
        bin.install "ory"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ory/cli/releases/download/v0.1.32/ory_0.1.32-macOS_sqlite_arm64.tar.gz"
      sha256 "5ebf407ffe3c140e0fad2099bcc1893cfd700d9c35191236bfec6c7e149dad8e"

      def install
        bin.install "ory"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ory/cli/releases/download/v0.1.32/ory_0.1.32-linux_sqlite_64bit.tar.gz"
      sha256 "8e8863969a7083eb53b44f9f2a7e11c4a2d585ce17cea58a7c6c45dd4722ff79"

      def install
        bin.install "ory"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/ory/cli/releases/download/v0.1.32/ory_0.1.32-linux_sqlite_armv6.tar.gz"
      sha256 "3b4245cd817bdc8e6990ff9bbc0c15ea1f1b2a6eb0ab300944a1f39d3c469852"

      def install
        bin.install "ory"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ory/cli/releases/download/v0.1.32/ory_0.1.32-linux_sqlite_arm64.tar.gz"
      sha256 "b6cb161f94f00a9d244085b31cbf2a3e033a09b7add6054b9f80a3e6d399ea48"

      def install
        bin.install "ory"
      end
    end
  end

  test do
    system "#{bin}/ory version"
  end
end
