# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hydra < Formula
  desc "The Ory OAuth2 and OpenID Connect Platform (Ory Hydra)"
  homepage "https://www.ory.sh"
  version "1.11.8"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ory/hydra/releases/download/v1.11.8/hydra_1.11.8-macOS_sqlite_64bit.tar.gz"
      sha256 "1b73a8589c0c36f87f1e8c15985339c29fde201ed296b0d99d0489239c24a45b"

      def install
        bin.install "hydra"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ory/hydra/releases/download/v1.11.8/hydra_1.11.8-macOS_sqlite_arm64.tar.gz"
      sha256 "46f233ec131ed3cea45db0f431113ce7720a78c874c1ae4e5c47f36b48a90b51"

      def install
        bin.install "hydra"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/ory/hydra/releases/download/v1.11.8/hydra_1.11.8-linux_sqlite_armv6.tar.gz"
      sha256 "09561e60a8471a7d76d132273fd5841269ea3b942ad213b0c165695490045445"

      def install
        bin.install "hydra"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ory/hydra/releases/download/v1.11.8/hydra_1.11.8-linux_sqlite_arm64.tar.gz"
      sha256 "a6e492bae03cf77604f11f95ada9bc0efc86599bed116d57bde22c6130fd69f0"

      def install
        bin.install "hydra"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ory/hydra/releases/download/v1.11.8/hydra_1.11.8-linux_sqlite_64bit.tar.gz"
      sha256 "83968a52a131b7e9c6422592aae5ee2cfd13297d6c3ef53df420943e137dba35"

      def install
        bin.install "hydra"
      end
    end
  end

  test do
    system "#{bin}/hydra version"
  end
end
