# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hydra < Formula
  desc "The Ory OAuth2 and OpenID Connect Platform (Ory Hydra)"
  homepage "https://www.ory.sh"
  version "2.0.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ory/hydra/releases/download/v2.0.3/hydra_2.0.3-macOS_sqlite_arm64.tar.gz"
      sha256 "884c38347f2f978ba25de5e08eaff474d4a340bc80ee85a7cb22d44aa981c172"

      def install
        bin.install "hydra"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ory/hydra/releases/download/v2.0.3/hydra_2.0.3-macOS_sqlite_64bit.tar.gz"
      sha256 "8f1437f15c0c7de2cccbc4b25f879c3b9f2883597daf7e6cfbf03e80e5cdad2e"

      def install
        bin.install "hydra"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ory/hydra/releases/download/v2.0.3/hydra_2.0.3-linux_sqlite_64bit.tar.gz"
      sha256 "8914688840bb67ff38e78b499a2029b30282754cd7690f99dfc54f958fbd51c1"

      def install
        bin.install "hydra"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/ory/hydra/releases/download/v2.0.3/hydra_2.0.3-linux_sqlite_armv6.tar.gz"
      sha256 "9d2c6a8ed3387115c02d9c1a93ad18f4830f2a9e0d94db77173944fef09828b1"

      def install
        bin.install "hydra"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ory/hydra/releases/download/v2.0.3/hydra_2.0.3-linux_sqlite_arm64.tar.gz"
      sha256 "ff33972dbcc7dcaef3d641913b7373d0aa7a9d0caadbf76190df9b43e2a0a596"

      def install
        bin.install "hydra"
      end
    end
  end

  test do
    system "#{bin}/hydra version"
  end
end
