# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Keto < Formula
  desc "The Ory Authorization Server (Ory Keto)"
  homepage "https://www.ory.sh"
  version "0.8.0-alpha.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ory/keto/releases/download/v0.8.0-alpha.1/keto_0.8.0-alpha.1-macOS_sqlite_64bit.tar.gz"
      sha256 "20ccb4c4028e27cf34bc8b2cb8d864930fa2899ccbfb7271f4daee87df6ab87b"

      def install
        bin.install "keto"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ory/keto/releases/download/v0.8.0-alpha.1/keto_0.8.0-alpha.1-macOS_sqlite_arm64.tar.gz"
      sha256 "30f3c8e3c46fdb786b9619184e415ecdaff044d16750d2901283aaccc7a7c050"

      def install
        bin.install "keto"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ory/keto/releases/download/v0.8.0-alpha.1/keto_0.8.0-alpha.1-linux_sqlite_64bit.tar.gz"
      sha256 "2177b8268f7a015c4154c61457cb4703210707ae84b0a3b1159e4e75db3e6e23"

      def install
        bin.install "keto"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ory/keto/releases/download/v0.8.0-alpha.1/keto_0.8.0-alpha.1-linux_sqlite_arm64.tar.gz"
      sha256 "d74c4b9cd688ccde2ab73436356120042568332f9b7c00c06651b153e484f2cf"

      def install
        bin.install "keto"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/ory/keto/releases/download/v0.8.0-alpha.1/keto_0.8.0-alpha.1-linux_sqlite_armv6.tar.gz"
      sha256 "a9d3c143b7826c5f0d6ccc52be4e8300724113845e7db01d5644637210b98803"

      def install
        bin.install "keto"
      end
    end
  end

  test do
    system "#{bin}/keto version"
  end
end
