# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Keto < Formula
  desc "The Ory Authorization Server (Ory Keto)"
  homepage "https://www.ory.sh"
  version "0.11.1-alpha.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ory/keto/releases/download/v0.11.1-alpha.0/keto_0.11.1-alpha.0-macOS_sqlite_arm64.tar.gz"
      sha256 "c0cb6d424295c0ce091cdff0ea58dc0c8b9c49bf57c9b17bc17d0d795184298d"

      def install
        bin.install "keto"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ory/keto/releases/download/v0.11.1-alpha.0/keto_0.11.1-alpha.0-macOS_sqlite_64bit.tar.gz"
      sha256 "976de48d1ef07fa501b578cd8e4f6179d9fbdc22ce6be90bf73b417497a2069a"

      def install
        bin.install "keto"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ory/keto/releases/download/v0.11.1-alpha.0/keto_0.11.1-alpha.0-linux_sqlite_64bit.tar.gz"
      sha256 "232e36150c4c7f661d0b45c7bdb4d63bfb295a8f42ed3b042aaa4828c8bca168"

      def install
        bin.install "keto"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/ory/keto/releases/download/v0.11.1-alpha.0/keto_0.11.1-alpha.0-linux_sqlite_armv6.tar.gz"
      sha256 "2184e6bd91b4362864b3eb4ea5a563550ab5454724f4e6a3cacee6f0420be698"

      def install
        bin.install "keto"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ory/keto/releases/download/v0.11.1-alpha.0/keto_0.11.1-alpha.0-linux_sqlite_arm64.tar.gz"
      sha256 "07da461e7a94a6275922715f64fcd5d0499c5aed62fe98ab6db70aadc10acc8e"

      def install
        bin.install "keto"
      end
    end
  end

  test do
    system "#{bin}/keto version"
  end
end
