# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Keto < Formula
  desc "The Ory Authorization Server (Ory Keto)"
  homepage "https://www.ory.sh"
  version "25.4.0-pre.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ory/keto/releases/download/v25.4.0-pre.0/keto_25.4.0-pre.0-macOS_sqlite_64bit.tar.gz"
      sha256 "5eab78317af90e4ecbea7ba1227c9a4946d69d90deb71f1bf7009298ea99dc6d"

      def install
        bin.install "keto"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ory/keto/releases/download/v25.4.0-pre.0/keto_25.4.0-pre.0-macOS_sqlite_arm64.tar.gz"
      sha256 "ecb1508fe853fa2717d8752ac997df3ba95204c21479edfa85802a6c85f42ec5"

      def install
        bin.install "keto"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ory/keto/releases/download/v25.4.0-pre.0/keto_25.4.0-pre.0-linux_sqlite_64bit.tar.gz"
      sha256 "5545371aa92834b88076058ea151ab2c75003045e5a22d46987ee7e8e1ea9fdc"
      def install
        bin.install "keto"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/ory/keto/releases/download/v25.4.0-pre.0/keto_25.4.0-pre.0-linux_sqlite_armv6.tar.gz"
      sha256 "45363fcc8eb5341d05dbc3e468061d957528459865959e270a3d26fe40925027"
      def install
        bin.install "keto"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ory/keto/releases/download/v25.4.0-pre.0/keto_25.4.0-pre.0-linux_sqlite_arm64.tar.gz"
      sha256 "3f1af2b0438537006921c543fb8618148999485889b192bda2a992eee3d8f97d"
      def install
        bin.install "keto"
      end
    end
  end

  test do
    system "#{bin}/keto version"
  end
end
