# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kratos < Formula
  desc "The Ory Identity Platform (Ory Kratos)"
  homepage "https://www.ory.sh"
  version "1.3.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/ory/kratos/releases/download/v1.3.0/kratos_1.3.0-macOS_sqlite_64bit.tar.gz"
      sha256 "457758fa92b32a61d531deb874136ce4259a1684499f712129652169d2aef0e2"

      def install
        bin.install "kratos"
      end
    end
    on_arm do
      url "https://github.com/ory/kratos/releases/download/v1.3.0/kratos_1.3.0-macOS_sqlite_arm64.tar.gz"
      sha256 "02dadea02b67cd708563d8c8cff2907ccd57a7a1054d98c34d20507c991e4f7c"

      def install
        bin.install "kratos"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ory/kratos/releases/download/v1.3.0/kratos_1.3.0-linux_sqlite_64bit.tar.gz"
        sha256 "a40c13824fc50cf174b4783ada4fe17179945027d38956914741662d5ae3a97e"

        def install
          bin.install "kratos"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/ory/kratos/releases/download/v1.3.0/kratos_1.3.0-linux_sqlite_armv6.tar.gz"
        sha256 "6addefa2e63a13a36d28c76d5b49f7dae9da9994f8d17cdfbe88343b3221fe2c"

        def install
          bin.install "kratos"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ory/kratos/releases/download/v1.3.0/kratos_1.3.0-linux_sqlite_arm64.tar.gz"
        sha256 "23fdd231cb9747ddb4d30ff7b56fe536adf2dec1da84c89b7a57d275b0a38b2c"

        def install
          bin.install "kratos"
        end
      end
    end
  end

  test do
    system "#{bin}/kratos version"
  end
end
