# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kratos < Formula
  desc "The Ory Kratos Identity Platform"
  homepage "https://www.ory.sh"
  version "0.8.0-alpha.2.pre.6"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ory/kratos/releases/download/v0.8.0-alpha.2.pre.6/kratos_0.8.0-alpha.2.pre.6-macOS_sqlite_64bit.tar.gz"
      sha256 "739123fafd3f4402c8eefa451461a69c1119a04ea23443151269251052c9c880"

      def install
        bin.install "kratos"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ory/kratos/releases/download/v0.8.0-alpha.2.pre.6/kratos_0.8.0-alpha.2.pre.6-macOS_sqlite_arm64.tar.gz"
      sha256 "e1faf6a9be97a726a42dd5acafbc047087026a1504299482f101af04e052492c"

      def install
        bin.install "kratos"
      end
    end
    url "https://github.com/ory/kratos/releases/download/v0.8.0-alpha.2.pre.6/kratos_0.8.0-alpha.2.pre.6-macOS_sqlite_all.tar.gz"
    sha256 "51a9c3be7e45b68badcd4cc76660efb66ca4bafd3282d6da40b5769c09549ab6"

    def install
      bin.install "kratos"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ory/kratos/releases/download/v0.8.0-alpha.2.pre.6/kratos_0.8.0-alpha.2.pre.6-linux_sqlite_64bit.tar.gz"
      sha256 "41c556e50eecedc7a74750cd1477f7e92c401e977535a34f0b4347e87adb3010"

      def install
        bin.install "kratos"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ory/kratos/releases/download/v0.8.0-alpha.2.pre.6/kratos_0.8.0-alpha.2.pre.6-linux_sqlite_arm64.tar.gz"
      sha256 "7c0fbf45f0294f9b31c8d412abde26320ec9891bb4f0f4b2eeaadc69e81cec6f"

      def install
        bin.install "kratos"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/ory/kratos/releases/download/v0.8.0-alpha.2.pre.6/kratos_0.8.0-alpha.2.pre.6-linux_sqlite_armv6.tar.gz"
      sha256 "d75ce0c893cdfb3002f6699e880140dbf1dd0b7518ee5224430299e224f661dc"

      def install
        bin.install "kratos"
      end
    end
  end

  test do
    system "#{bin}/kratos version"
  end
end
