# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kratos < Formula
  desc "The Ory Identity Platform (Ory Kratos)"
  homepage "https://www.ory.sh"
  version "0.10.0-pre.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ory/kratos/releases/download/v0.10.0-pre.0/kratos_0.10.0-pre.0-macOS_sqlite_64bit.tar.gz"
      sha256 "3164ceee7185236a54343b6996876d9182f866e41a37e60413869675826b3290"

      def install
        bin.install "kratos"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ory/kratos/releases/download/v0.10.0-pre.0/kratos_0.10.0-pre.0-macOS_sqlite_arm64.tar.gz"
      sha256 "9dddc7c6875d07bf856adf52f9eb1227dd358260ba81e3a73ecf84f65ac8687d"

      def install
        bin.install "kratos"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ory/kratos/releases/download/v0.10.0-pre.0/kratos_0.10.0-pre.0-linux_sqlite_arm64.tar.gz"
      sha256 "90beb525ab9f8b059bf9ff26e3ba132f3bedd4e27d52255f6cbb5538253190eb"

      def install
        bin.install "kratos"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ory/kratos/releases/download/v0.10.0-pre.0/kratos_0.10.0-pre.0-linux_sqlite_64bit.tar.gz"
      sha256 "6b1b36598397121fb6562dc062a1ca1da5e5463db0aa151451283bb24f5a303d"

      def install
        bin.install "kratos"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/ory/kratos/releases/download/v0.10.0-pre.0/kratos_0.10.0-pre.0-linux_sqlite_armv6.tar.gz"
      sha256 "e575e10733662bfde26010ac4ea6e62ecfb6d6ee2141f403ac5bd3220c1b9470"

      def install
        bin.install "kratos"
      end
    end
  end

  test do
    system "#{bin}/kratos version"
  end
end
