# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oathkeeper < Formula
  desc "The Ory Identity and Access Proxy (Ory Oathkeeper)"
  homepage "https://www.ory.sh"
  version "25.4.0-pre.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ory/oathkeeper/releases/download/v25.4.0-pre.0/oathkeeper_25.4.0-pre.0-macOS_sqlite_64bit.tar.gz"
      sha256 "0435452bfaa71a7606d1ba3e4f080a9f60662b941778faefdd09a8f20971cd18"

      def install
        bin.install "oathkeeper"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ory/oathkeeper/releases/download/v25.4.0-pre.0/oathkeeper_25.4.0-pre.0-macOS_sqlite_arm64.tar.gz"
      sha256 "c1d20474366c262367fbad3f02736c3e020b3dcf00e235da6cffd1922037fe70"

      def install
        bin.install "oathkeeper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ory/oathkeeper/releases/download/v25.4.0-pre.0/oathkeeper_25.4.0-pre.0-linux_sqlite_64bit.tar.gz"
      sha256 "62507779ccb31b1f5445f8d42dee44941b8eceb4b5ab0bac3cbd11cae0b58323"
      def install
        bin.install "oathkeeper"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/ory/oathkeeper/releases/download/v25.4.0-pre.0/oathkeeper_25.4.0-pre.0-linux_sqlite_armv6.tar.gz"
      sha256 "48e6cffc275cd45289c28e44e397bac62698147092caa6798e25d1340d2c7cf8"
      def install
        bin.install "oathkeeper"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ory/oathkeeper/releases/download/v25.4.0-pre.0/oathkeeper_25.4.0-pre.0-linux_sqlite_arm64.tar.gz"
      sha256 "8eaa0f8dadbafd60b8a4905d3cb180d89f425dab487923d4465dea589a4114fa"
      def install
        bin.install "oathkeeper"
      end
    end
  end

  test do
    system "#{bin}/oathkeeper version"
  end
end
