# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oathkeeper < Formula
  desc "The Ory Identity and Access Proxy (Ory Oathkeeper)"
  homepage "https://www.ory.sh"
  version "0.39.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ory/oathkeeper/releases/download/v0.39.0/oathkeeper_0.39.0-macOS_sqlite_arm64.tar.gz"
      sha256 "6c049d03d584fdd7cd00ce152349899293ed1934531e9440bf03e3855755ce78"

      def install
        bin.install "oathkeeper"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ory/oathkeeper/releases/download/v0.39.0/oathkeeper_0.39.0-macOS_sqlite_64bit.tar.gz"
      sha256 "c7424b6ce49c0370783b54cc471bd963929decc534f259262df2710c9c5b4306"

      def install
        bin.install "oathkeeper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/ory/oathkeeper/releases/download/v0.39.0/oathkeeper_0.39.0-linux_sqlite_armv6.tar.gz"
      sha256 "ddb05c833211f0b944cb2596d20d9d1192e2d9176eefe71877c1c8f00c1e8885"

      def install
        bin.install "oathkeeper"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ory/oathkeeper/releases/download/v0.39.0/oathkeeper_0.39.0-linux_sqlite_64bit.tar.gz"
      sha256 "c72e119365e1aaf081ade6241af02650505e9618393f6aa4b82c948a9e8574f2"

      def install
        bin.install "oathkeeper"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ory/oathkeeper/releases/download/v0.39.0/oathkeeper_0.39.0-linux_sqlite_arm64.tar.gz"
      sha256 "67fcfcf4c3c7e6571d1136050309729c2d3a687f7cb9d3ceebec95d9a8c1df5a"

      def install
        bin.install "oathkeeper"
      end
    end
  end

  test do
    system "#{bin}/oathkeeper version"
  end
end
