# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oathkeeper < Formula
  desc "The Ory Identity and Access Proxy (Ory Oathkeeper)"
  homepage "https://www.ory.sh"
  version "0.38.22-beta.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ory/oathkeeper/releases/download/v0.38.22-beta.1/oathkeeper_0.38.22-beta.1-macOS_sqlite_arm64.tar.gz"
      sha256 "e253ba2f36be41595cb7cda622e1bc9865afc7ba9775c500cc47c9b3cdd4d03e"

      def install
        bin.install "oathkeeper"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ory/oathkeeper/releases/download/v0.38.22-beta.1/oathkeeper_0.38.22-beta.1-macOS_sqlite_64bit.tar.gz"
      sha256 "0d11e2b8ae075bf6f38e97bc87c47c813c935737f2380e0d95d9cb3e1b87b6e5"

      def install
        bin.install "oathkeeper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/ory/oathkeeper/releases/download/v0.38.22-beta.1/oathkeeper_0.38.22-beta.1-linux_sqlite_armv6.tar.gz"
      sha256 "7da3ae7c09ad4417339d071f0430fe44d21fbeedb15db774b4c9d58d5b278414"

      def install
        bin.install "oathkeeper"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ory/oathkeeper/releases/download/v0.38.22-beta.1/oathkeeper_0.38.22-beta.1-linux_sqlite_64bit.tar.gz"
      sha256 "045fbe82a865a5bf9b6eccbc5b97c1862f7828997dfe6586a670eb9952432ed7"

      def install
        bin.install "oathkeeper"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ory/oathkeeper/releases/download/v0.38.22-beta.1/oathkeeper_0.38.22-beta.1-linux_sqlite_arm64.tar.gz"
      sha256 "6f39dbb9e86850a23b5ebe88e8991a408d9a9bb3c6d45bb223560c8cc1d10b83"

      def install
        bin.install "oathkeeper"
      end
    end
  end

  test do
    system "#{bin}/oathkeeper version"
  end
end
