# typed: false
# frozen_string_literal: true

# This file is generated by the ory-agent release workflow. DO NOT EDIT.
class OryAgent < Formula
  desc "Deploy and manage Ory Agent Security runtime identities"
  homepage "https://www.ory.com/"
  version "1.4.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ory/ory-agent/releases/download/v1.4.4/ory-agent_1.4.4_darwin_amd64.tar.gz"
      sha256 "46f67aa996688c29375e7ea94c59cce1a035679d3274d5f8bd12362ff10352c4"
    end
    if Hardware::CPU.arm?
      url "https://github.com/ory/ory-agent/releases/download/v1.4.4/ory-agent_1.4.4_darwin_arm64.tar.gz"
      sha256 "1488a2e489604843b3849c5b1dbfcf3eabd422043f58537472307518671943ed"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ory/ory-agent/releases/download/v1.4.4/ory-agent_1.4.4_linux_amd64.tar.gz"
      sha256 "6e0d372c8d067d1d313477023578691964c137a0e603bb6f4a4926f5ff7cfed4"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ory/ory-agent/releases/download/v1.4.4/ory-agent_1.4.4_linux_arm64.tar.gz"
      sha256 "6aa0909d00c6ab72e1ca6080c6485d7e36e99e443cd47636450981031c6abb3c"
    end
  end

  def install
    bin.install "ory-agent"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ory-agent version")
  end
end
