# typed: false
# frozen_string_literal: true

# This file is generated by the ory-agent release workflow. DO NOT EDIT.
class OryAgent < Formula
  desc "Deploy and manage Ory Agent Security runtime identities"
  homepage "https://www.ory.com/"
  version "1.4.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ory/ory-agent/releases/download/v1.4.3/ory-agent_1.4.3_darwin_amd64.tar.gz"
      sha256 "2febc777e71b80f0ad720eee3c2a573871883c2e7a636ed06b023c5d89b62bcb"
    end
    if Hardware::CPU.arm?
      url "https://github.com/ory/ory-agent/releases/download/v1.4.3/ory-agent_1.4.3_darwin_arm64.tar.gz"
      sha256 "7916196e35079afd0b34dac8063801d0416dbf935a82f64ceabb5358fad39aed"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ory/ory-agent/releases/download/v1.4.3/ory-agent_1.4.3_linux_amd64.tar.gz"
      sha256 "54806171d484303df432b5f05a5448aea414b36f8740ef3ddfed5f44ce127e6c"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ory/ory-agent/releases/download/v1.4.3/ory-agent_1.4.3_linux_arm64.tar.gz"
      sha256 "943a9e1f1e243d95827405b50288c222b63dddc38e3b41b89cdfaf325af41195"
    end
  end

  def install
    bin.install "ory-agent"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ory-agent version")
  end
end
