# typed: false
# frozen_string_literal: true

# This file is generated by the ory-agent release workflow. DO NOT EDIT.
class OryAgent < Formula
  desc "Deploy and manage Ory Agent Security runtime identities"
  homepage "https://www.ory.com/"
  version "1.4.6"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ory/ory-agent/releases/download/v1.4.6/ory-agent_1.4.6_darwin_amd64.tar.gz"
      sha256 "4d4e57347a169fef485e966147983a725e68a0e8bbc7caefa7d9df75df03380c"
    end
    if Hardware::CPU.arm?
      url "https://github.com/ory/ory-agent/releases/download/v1.4.6/ory-agent_1.4.6_darwin_arm64.tar.gz"
      sha256 "b0f9b758e1ddd33efe183bb8cf3b6d82f17e12408e53fe510a5e35fbca932e16"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ory/ory-agent/releases/download/v1.4.6/ory-agent_1.4.6_linux_amd64.tar.gz"
      sha256 "47c39b3c62548b007bf0b578694860ea4c56d8d7d0b1a524dc2338ae2fc094bf"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ory/ory-agent/releases/download/v1.4.6/ory-agent_1.4.6_linux_arm64.tar.gz"
      sha256 "fd4fee6bc5f3c160f74c2ea9683146b0943ff5692c158261391a526593daadf9"
    end
  end

  def install
    bin.install "ory-agent"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/ory-agent version")
  end
end
