# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Talos < Formula
  desc "The Ory API Credential Management Platform (Ory Talos)"
  homepage "https://www.ory.sh"
  version "0.0.0-alpha.1.pre.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ory/talos/releases/download/v0.0.0-alpha.1.pre.4/talos_0.0.0-alpha.1.pre.4-macOS_sqlite_64bit.tar.gz"
      sha256 "dd7ca11709cbfb042280ec4a20dce2462da13ebaab41f534998422a446724541"

      define_method(:install) do
        bin.install "talos"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ory/talos/releases/download/v0.0.0-alpha.1.pre.4/talos_0.0.0-alpha.1.pre.4-macOS_sqlite_arm64.tar.gz"
      sha256 "37c20a331fcfe6af0de2ed2f69a1442e4da2d1385769fb30138052206b3ff2ce"

      define_method(:install) do
        bin.install "talos"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ory/talos/releases/download/v0.0.0-alpha.1.pre.4/talos_0.0.0-alpha.1.pre.4-linux_sqlite_64bit.tar.gz"
      sha256 "e8201028e1b00211f00c13412338b4ae2fffa9e6e8e82d724b53125e79cf7dff"
      define_method(:install) do
        bin.install "talos"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/ory/talos/releases/download/v0.0.0-alpha.1.pre.4/talos_0.0.0-alpha.1.pre.4-linux_sqlite_armv6.tar.gz"
      sha256 "6470dc58daa03aaa0af69a6097586b03db0a0531a1711be23722462190f82e35"
      define_method(:install) do
        bin.install "talos"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ory/talos/releases/download/v0.0.0-alpha.1.pre.4/talos_0.0.0-alpha.1.pre.4-linux_sqlite_arm64.tar.gz"
      sha256 "05fe172d966e9cb7bfd6490b019564fd2fe3f3859f3e2e2322f485cc94266c57"
      define_method(:install) do
        bin.install "talos"
      end
    end
  end

  test do
    system "#{bin}/talos version"
  end
end
