# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Talos < Formula
  desc "The Ory API Credential Management Platform (Ory Talos)"
  homepage "https://www.ory.sh"
  version "26.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ory/talos/releases/download/v26.2.0/talos_26.2.0-macOS_sqlite_64bit.tar.gz"
      sha256 "36813381052d18661eb5996ac872a6fae2eb6146e9213143aa10036ed094fc7d"

      define_method(:install) do
        bin.install "talos"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ory/talos/releases/download/v26.2.0/talos_26.2.0-macOS_sqlite_arm64.tar.gz"
      sha256 "fb7318daee3c7a0e00496e57569991b4f5023029b2b4b2ba7f90212f1f460c9e"

      define_method(:install) do
        bin.install "talos"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ory/talos/releases/download/v26.2.0/talos_26.2.0-linux_sqlite_64bit.tar.gz"
      sha256 "9a659029d0ffd060119288bdac3576977d560feb9c6199851b3c5d863ccd1895"
      define_method(:install) do
        bin.install "talos"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/ory/talos/releases/download/v26.2.0/talos_26.2.0-linux_sqlite_armv6.tar.gz"
      sha256 "8f21808b638e6d7fd06e5e88dc0634746d1b6454621c6a1c2ea1177461ceab61"
      define_method(:install) do
        bin.install "talos"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ory/talos/releases/download/v26.2.0/talos_26.2.0-linux_sqlite_arm64.tar.gz"
      sha256 "e906f418cf5641686324b080e8c6f8388de1507e103a0d1bf4091883c465cbde"
      define_method(:install) do
        bin.install "talos"
      end
    end
  end

  test do
    system "#{bin}/talos version"
  end
end
