# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Talos < Formula
  desc "The Ory API Credential Management Platform (Ory Talos)"
  homepage "https://www.ory.sh"
  version "0.0.0-alpha.1.pre.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ory/talos/releases/download/v0.0.0-alpha.1.pre.3/talos_0.0.0-alpha.1.pre.3-macOS_sqlite_64bit.tar.gz"
      sha256 "39c29476d42cd3c5790e8fa07320d935a1a60975353c7ef93205277b9521c377"

      define_method(:install) do
        bin.install "talos"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ory/talos/releases/download/v0.0.0-alpha.1.pre.3/talos_0.0.0-alpha.1.pre.3-macOS_sqlite_arm64.tar.gz"
      sha256 "32df6c1d281b8b05cac8cf9d2e0b0ef75bd843bbf4ec316fcb50970b06cb24cf"

      define_method(:install) do
        bin.install "talos"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ory/talos/releases/download/v0.0.0-alpha.1.pre.3/talos_0.0.0-alpha.1.pre.3-linux_sqlite_64bit.tar.gz"
      sha256 "8cffe304cc7d3e548cbe718ac35c47c0c48b48ada4fb6fdd292c44113f75f09f"
      define_method(:install) do
        bin.install "talos"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/ory/talos/releases/download/v0.0.0-alpha.1.pre.3/talos_0.0.0-alpha.1.pre.3-linux_sqlite_armv6.tar.gz"
      sha256 "b9940b1ccc676bda575a604efef1aeeb2e99dc1c75c1c24d0c83bb2fbf0ad765"
      define_method(:install) do
        bin.install "talos"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ory/talos/releases/download/v0.0.0-alpha.1.pre.3/talos_0.0.0-alpha.1.pre.3-linux_sqlite_arm64.tar.gz"
      sha256 "ad59f310359f2595a86df5ac0003b92f8d4fc5efddd7dd7d9388303b6b29e340"
      define_method(:install) do
        bin.install "talos"
      end
    end
  end

  test do
    system "#{bin}/talos version"
  end
end
